#!/usr/bin/env bash

# Gather all of the system and user crontab scheduled jobs and display them
# in a consolidated table, sorted approximately by the scheduled time.

# This file is part of Scripnix. Copyright 2016 Dave Rogers <info@yukondude.com>. Licensed under the GNU General Public License, version 3.
# Refer to the attached LICENSE file or see <http://www.gnu.org/licenses/> for details.

scriproot=$(whereis-scripnix)
source "${scriproot}/conf/sbin.bash"
check_arg_count ${0} ${#} 0 0 '' ${1}

gather-cron-jobs --run-parts --sort | column -s"	" -t
